#!/usr/bin/env node
// Build the generated files in static/, which are committed:
//
//   static/vendor/codemirror.js  CodeMirror, for the playground
//   static/client.js             the library for shows on other sites,
//                                from js/client-main.js, js/stairs.js,
//                                and js/bulb.js
//
//   npm run build:vendor

import fs from 'node:fs';
import {build} from 'esbuild';

const staticDir = new URL('../static/', import.meta.url);

await build({
  stdin: {
    contents: `
      export {EditorView} from 'codemirror';
      export {editorSetup} from './editor-setup.js';
      export {EditorState, Prec} from '@codemirror/state';
      export {keymap} from '@codemirror/view';
      export {indentWithTab} from '@codemirror/commands';
      export {javascript} from '@codemirror/lang-javascript';
      export {syntaxTree} from '@codemirror/language';
    `,
    resolveDir: import.meta.dirname,
  },
  bundle: true,
  format: 'esm',
  minify: true,
  legalComments: 'eof',
  outfile: new URL('vendor/codemirror.js', staticDir).pathname,
});

await build({
  entryPoints: [new URL('js/client-main.js', staticDir).pathname],
  bundle: true,
  format: 'iife',
  target: 'es2022',
  banner: {js: `// Blinken client library: https://blinken.org/
// Generated by server/build-vendor.js from static/js/client-main.js,
// stairs.js, and bulb.js. Edit those instead.

${fs.readFileSync(new URL('js/bulb.js', staticDir), 'utf8')}`},
  outfile: new URL('client.js', staticDir).pathname,
});
